databases:
  - name: ecommerce_02oe
    plan: free
    databaseName: ecommerce
    user: ecommerce_02oe_user
    
services:
  - type: web
    plan: free
    name: ecommerce_02oe
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ecommerce.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce_02oe
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 
